port = 45777
map = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
    [1, 2, 1, 0, 0, 0, 1, 0, 0, 1], 
    [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], 
    [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], 
    [1, 0, 0, 0, 1, 0, 0, 0, 0, 1], 
    [1, 0, 1, 0, 1, 1, 0, 2, 0, 1], 
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 1], 
    [1, 0, 1, 1, 1, 1, 1, 1, 0, 1], 
    [1, 0, 0, 0, 1, 0, 0, 0, 0, 1], 
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
]

# Map config:
# 0 = empty space
# 1 = wall
# 2 = player spawn point
# 3 = objective point